alias ..="cd .."
alias mkdir="mkdir -p"
alias rm="rm -r"
alias ls="ls --human-readable --color=auto"
alias la="ls -la"
alias sdn="sudo shutdown -h now"
alias cl="clear"

# Programs
alias gs="git status"
alias gadd="git add --all"
alias autostow="(cd ~/dotfiles; ~/dotfiles/autostow.sh)"
alias reboot="sudo systemctl reboot"
alias poweroff="sudo systemctl poweroff"


#Aliases for edit dotfiles
alias dot='cd ~/.dotfiles'
alias autostow="~/.dotfiles/autostow.sh"
alias stowedit="vim ~/.dotfiles/autostow.sh"
alias zshrcedit="vim ~/.dotfiles/zsh/.zshrc"
alias aliasedit="vim ~/.dotfiles/zsh/.zsh_aliases; source ~/.zshrc"
alias alacrittyedit="vim ~/.dotfiles/alacritty/alacritty.yml"
alias vimrcedit="vim ~/.dotfiles/vim/.vimrc"
alias bspwmrcedit="vim ~/.dotfiles/bspwm/bspwmrc"
alias sxhkdrcedit="vim ~/.dotfiles/sxhkd/sxhkdrc"
alias picomedit="vim ~/.dotfiles/picom/picom.conf"
alias packagesedit="vim ~/.dotfiles/install/packages.sh"
alias snippetsedit="vim ~/.dotfiles/nvim/UltiSnips/tex.snippets"
