alias ..="cd .."
alias mkdir="mkdir -p"
alias rm="rm -r"
alias ls="ls --human-readable --color=auto"
alias la="ls -la"
alias sdn="sudo shutdown -h now"
alias cl="clear"

# Programs
alias gs="git status"
alias addall="git add --all"
alias g++c="g++ --std=c++17 -Wall -O2 -fsanitize=address"
alias autostow="(cd ~/dotfiles; ~/dotfiles/autostow.sh)"
alias reboot="sudo systemctl reboot"
alias poweroff="sudo systemctl poweroff"
alias halt="sudo systemctl halt"
